MicrosoftDX/Vorlonjs

- Server/public/stylesheets/components/buttons.styl
- Server/public/stylesheets/components/sidebar.styl
- Server/views/includes/sidebar.jade
- package.json
I'm not sure what it's actually supposed to do, as there doesn't seem to be a reset function on vorlonDashboard, so @meulta you'll need to add that.
> Added a reset button.

- Plugins/Vorlon/plugins/domExplorer/control.css
First project commit, let me know if this is a desired change.
> Adding overflow ellipsis to CSS prop/val text

- Plugins/Vorlon/plugins/domExplorer/vorlon.domExplorer.ts
Fixed issue with null reference in node tree.  https://github.com/MicrosoftDX/Vorlonjs/issues/36
(The other changes are where the editor removes end-of line spaces)
> Fixed issue with null reference in node tree. 

- Plugins/Vorlon/plugins/modernizrReport/control.css
- Plugins/Vorlon/plugins/modernizrReport/control.html
- Plugins/Vorlon/plugins/modernizrReport/vorlon.modernizrReport.ts
- Server/public/vorlon.dashboardManager.ts
I have added UI and functionality that allows you to live filter the feature list in the Modernizr panel. before I do more to merge it I have one question: where in the plugin class does can I get a hook to when all the features in the table are populated? Right now, as a stopgap, I just build the object dict on each focus of the filtering input, but that's not a great way to do it.
> DISCUSS FIRST: Added live filtering to Modernizr feature panel

- Plugins/Vorlon/plugins/domExplorer/vorlon.domExplorer.ts
CSS persistent changes updated.
> CSS persistent changes

- Plugins/Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.ts
record all commands issued in interactive console and allow user to get previous issued commands
with up/down arrows.
The history is "saved" per client and is lost if the user refreshe/changes client.
The commands are not shared betwen different users accessing the dashboard
> Added command history to Interactive Console

- Plugins/Vorlon/plugins/ngInspector/vorlon.ngInspector.ts
- Server/config.json
Fix bug https://github.com/MicrosoftDX/Vorlonjs/issues/128
> Fix bug #128

- Plugins/Plugins.csproj
- Plugins/Vorlon/plugins/networkMonitor/control.html
- Plugins/Vorlon/plugins/networkMonitor/control.less
- Plugins/Vorlon/plugins/networkMonitor/vorlon.networkMonitor.client.ts
- Plugins/Vorlon/plugins/networkMonitor/vorlon.networkMonitor.dashboard.ts
- Plugins/Vorlon/plugins/networkMonitor/vorlon.networkMonitor.interfaces.ts
- Plugins/Vorlon/plugins/resourcesExplorer/control.html
- Plugins/Vorlon/plugins/resourcesExplorer/control.less
- Plugins/Vorlon/plugins/resourcesExplorer/vorlon.resourcesExplorer.client.ts
- Plugins/Vorlon/plugins/resourcesExplorer/vorlon.resourcesExplorer.dashboard.ts
- Plugins/Vorlon/plugins/resourcesExplorer/vorlon.resourcesExplorer.interfaces.ts
- Plugins/gulpfile.js
- Server/Server.njsproj
- Server/config.json
https://github.com/MicrosoftDX/Vorlonjs/issues/95
https://github.com/MicrosoftDX/Vorlonjs/issues/88
> Network and Resources plugins :)

- Plugins/Vorlon/plugins/networkMonitor/vorlon.networkMonitor.client.ts
- Plugins/Vorlon/plugins/networkMonitor/vorlon.networkMonitor.dashboard.ts
- whatsnew.md
Updating whatsnew.md for Network and Resources plugins
From https://github.com/MicrosoftDX/Vorlonjs/pull/139
> whatsnew.md

- plugins library/README.md
- plugins library/wappalyzerReport/control.html
- plugins library/wappalyzerReport/control.less
- plugins library/wappalyzerReport/vorlon.wappalyzerReport.client.ts
- plugins library/wappalyzerReport/vorlon.wappalyzerReport.dashboard.ts
- plugins library/wappalyzerReport/vorlon.wappalyzerReport.interfaces.ts
- plugins library/wappalyzerReport/wappalyzer.js
Wappalyzer plugin first commit
https://github.com/MicrosoftDX/Vorlonjs/pull/141#issuecomment-114573035
> Wappalyzer plugin

- Server/Scripts/vorlon.dashboard.ts
- Server/Scripts/vorlon.server.ts
- Server/config.json
- Server/config/vorlon.baseurlconfig.ts
- Server/public/vorlon.dashboardManager.ts
- Server/views/dashboard.jade
> Urlprefixes

- .deployment
See https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site
> Add .deployment file so Kudu doesn't get confused by .sln file

- Server/Scripts/vorlon.webServer.ts
- Server/config.json
- Server/config/vorlon.httpconfig.ts
Saw this at fitc but it did not support changing the port without changing environment variables
> Put port in config.json

- Plugins/Vorlon/vorlon.clientPlugin.ts
- Plugins/Vorlon/vorlon.dashboardPlugin.ts
- Server/Scripts/vorlon.server.ts
- Server/Scripts/vorlon.webServer.ts
- Server/public/vorlon.dashboardManager.ts
- Server/views/dashboard.jade
- Server/views/getsession.jade
- Server/views/includes/dashboard-plugins.jade
- Server/views/layout.jade
- Server/views/login.jade
More details in here:
https://github.com/MicrosoftDX/Vorlonjs/issues/115
Example of nginx conf
```
Here is my nginx conf:
server {
listen              80;
listen              [::]:80;
server_name         some.server.com;
root                /var/www;
location /socket.io/ {
proxy_pass http://localhost:1337;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
}
location ^~ /vorlonjs/ {
proxy_pass       http://localhost:1337;
proxy_set_header Host      $host;
proxy_set_header X-Real-IP $remote_addr;
}
}
```
> Fix for issue 115

- Plugins/Vorlon/vorlon.clientMessenger.ts
- Plugins/Vorlon/vorlon.core.ts
- Server/Scripts/typings/vorlon/vorlon.clientMessenger.d.ts
- Server/Scripts/typings/vorlon/vorlon.core.d.ts
- Server/Scripts/vorlon.server.ts
- Server/public/stylesheets/components/buttons.styl
- Server/public/stylesheets/style.css
- Server/public/vorlon.dashboardManager.ts
- Server/views/includes/sidebar.jade
> Reload Enhancement

- Plugins/Vorlon/plugins/webstandards/dashboard.ts
- Plugins/Vorlon/plugins/webstandards/rules/webstandards.cssfallback.ts
- Plugins/Vorlon/plugins/webstandards/vorlon.webstandards.client.ts
No plugin has been injured during the making of this PR
> adding rule for css properties fallback to "best practices" plugin

- Plugins/samples/index.html
- Server/Scripts/vorlon.dashboard.ts
- Server/Scripts/vorlon.httpproxy.server.ts
- Server/Scripts/vorlon.server.ts
- Server/Scripts/vorlon.webServer.ts
- Server/Scripts/vorlon.winstonlogger.ts
- Server/config/vorlon.logconfig.ts
- Server/config/vorlon.redisconfig.ts
- Server/config/vorlon.servercontext.ts
- Server/public/vorlon.dashboardManager.ts
- Server/server.ts
refactoring (all server-side) for config and session management. The goal is to unlock new kinds of scenarios for Vorlon server runtime
> refactoring config and session management

- .vscode/launch.json
- Plugins/samples/.gitignore
- Plugins/samples/browsersync.js
- Plugins/samples/package.json
- Plugins/samples/readme.md
- Server/Scripts/typings/node/node.d.ts
- desktop/app/background.ts
- desktop/app/dasboardloaderrorpage.html
- desktop/app/mainpage.html
- desktop/app/mainpage.ts
- desktop/app/screens/info/app.info.ts
- desktop/app/stylesheets/main.less
- desktop/tasks/build.js
- desktop/todo.txt
- desktop/typings/github-electron/electron-prebuilt.d.ts
- desktop/typings/github-electron/github-electron-main.d.ts
- desktop/typings/github-electron/github-electron-renderer.d.ts
- desktop/typings/github-electron/github-electron.d.ts
style loading screen, add error page
> [desktop] fix bug occuring when opening dashboard for the first time

- Server/public/stylesheets/components/dashboard.styl
https://github.com/MicrosoftDX/Vorlonjs/issues/230
> Fix tab-bar size issues

- .vscode/launch.json
- gulpfile.js
Also added vscode launch configuration to debug typescript.
> Generating sourcemaps to allow debugging directly in typescript

- Plugins/Vorlon/plugins/domExplorer/control.less
- Plugins/Vorlon/plugins/domExplorer/vorlon.domExplorer.dashboard.ts
- Click on an absolute uri by holding the ctrl key will display its
content into another tab.
- Hover is effective too.
> DomExplorer : add uri click behaviors

- Plugins/Vorlon/plugins/domExplorer/control.less
- Plugins/Vorlon/plugins/domExplorer/vorlon.domExplorer.dashboard.ts
> DomExplorer : minor changes concerning the display

- Plugins/Vorlon/plugins/webstandards/vorlon.webstandards.dashboard.ts
> Minor grammar correction

- Plugins/Vorlon/plugins/webstandards/control.less
- Plugins/Vorlon/plugins/webstandards/vorlon.webstandards.dashboard.ts
- Add result overview for each group of rules
> Test's results enhancement + fixes

- Plugins/Vorlon/plugins/uwp/control.html
- Plugins/Vorlon/plugins/uwp/control.less
- Plugins/Vorlon/plugins/uwp/vorlon.uwp.client.ts
- Plugins/Vorlon/plugins/uwp/vorlon.uwp.dashboard.ts
- Plugins/Vorlon/plugins/uwp/vorlon.uwp.interfaces.ts
- Server/config.json
- Server/public/javascripts/smoothie.js
- Server/views/dashboard.jade
- gulpfile.js
monitor memory, CPU, and disk I/O for Windows 10 UWP
> plugin for monitoring Windows 10 UWP applications

- Plugins/Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.dashboard.ts
> Interactive console : Add console.log alias

- Server/views/httpproxy.jade
Because they don't have a valid href, <a> tags are neither keyboard focusable (tab after the textbox) nor presented as link. 
Since they have the class btn and look like buttons, I decided to apply the role button instead of link.
> Accessibility improvement
